name: inventario
description: Sistema de Inventario y Operaciones Mobile (Offline-first)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.0.1
  
  # Networking
  dio: ^5.4.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  
  # Firebase / Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  
  # UI Utilities
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  
  # Testing
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
