name: Flutter Build APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permite lanzar la compilación manualmente desde la web de GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./flutter
    
    env:
      FLUTTER_SUPPRESS_ANALYTICS: 1
      PUB_TELEMETRY_OPT_OUT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5' # Tu versión detectada
          channel: 'stable'
          cache: true

      - name: Disable analytics and clean
        run: |
          flutter config --no-analytics
          flutter clean

      - name: Get dependencies (Flutter)
        run: flutter pub get


      - name: Build APK (Release)
        run: flutter build apk --release --no-pub

      - name: List build output (Debug)
        run: |
          echo "Current directory: $(pwd)"
          ls -R build/app/outputs/flutter-apk/ || echo "APK directory not found"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: flutter/build/app/outputs/flutter-apk/app-release.apk

